version: "3"

volumes:
  search_engine_postgres_data: {}
  search_engine_postgres_data_backups: {}

services:

    postgres:
        image: postgres:11
        container_name: postgres_search_engine
        volumes:
            - search_engine_postgres_data:/var/lib/postgresql/data:Z
            - search_engine_postgres_data_backups:/backups:z
        env_file:
            - ./.envs/.local/.postgres
        ports:
            - "127.0.0.1:5432:5432"
        restart: always
